let bank ={
    'cpr':
        ["Critique of Pure Reason",
["Transcendental Doctrine of Elements",
    ["First Part, Transcendental Aesthetic",
        ["First Section, On space.",
            ["Metaphysical exposition of the concept of space.",
                [["a100", "b101"], "blablabla."]
            ],
            ["Transcendental exposition of the concept of space."]
        ],
        ["Second Section, On time.",
            ["Metaphysical exposition of the concept of time."],
            ["Transcendental exposition of the concept of time."],
            ["Conclusions from these concepts."],
            ["Elucidation."],
            ["General remarks on the transcendental aesthetic",
                [["a42", "b59"],
                    "<I.> It will first be necessary to explain as distinctly as possible our opinion in regard to the fundamental constitution of sensible cognition in general, in order to preclude all misinterpretation of it.<br>We have therefore wanted to say that all our intuition is nothing but the representation of appearance; that the things that we intuit are not in themselves what we intuit them to be, nor are their relations so constituted in themselves as they appear to us; and that if we remove our own subject or even only the subjective constitution of the senses in general, then all constitution, all relations of objects in space and time, indeed space and time themselves would disappear, and as appearances they cannot exist in themselves, but only in us. What may be the case with objects in themselves and abstracted from all this receptivity of our sensibility remains entirely unknown to us. We are acquainted with nothing except our way of perceiving them, which is peculiar to us, and which therefore does not necessarily pertain to every being, though to be sure it pertains to every human being."
                ],
                [["a43", "b60"],
                    "We are concerned solely with this. Space and time are its pure forms, sensation in general its matter. We can cognize only the former a priori, i.e., prior to all actual perception, and they are therefore called pure intuition; the latter, however, is that in our cognition that is responsible for it being called a posteriori cognition, i.e., empirical intuition. The former adheres to our sensibility absolutely necessarily, whatever sort of sensations we may have; the latter can be very different. Even if we could bring this intuition of ours to the highest degree of distinctness we would not thereby come any closer to the constitution of objects in themselves. For in any case we would still completely cognize only our own way of intuiting, i.e., our sensibility, and this always only under the conditions originally depending on the subject, space and time; what the objects may be in themselves would still never be known through the most enlightened cognition of their appearance, which alone is given to us.<br>That our entire sensibility is nothing but the confused representation of things, which contains solely that which pertains to them in themselves but only under a heap of marks and partial representations that we can never consciously separate from one another, is therefore a falsification of the concept of sensibility and of appearance that renders the entire theory of them useless and empty."
                ],
                [["a44", "b61"],
                    "The difference between an indistinct and a distinct representation is merely logical, and does not concern the content. Without doubt the concept of right that is used by the healthy understanding contains the very same things that the most subtle speculation can evolve out of it, only in common and practical use one is not conscious of these manifold representations in these thoughts. Thus one cannot say that the common concept is sensible and contains a mere appearance, for right cannot appear at all; rather its concept lies in the understanding and represents a constitution (the moral constitution) of actions that pertains to them in themselves. The representation of a body in intuition, on the contrary, contains nothing at all that could pertain to an object in itself, but merely the appearance of something and the way in which we are affected by it; and this receptivity of our cognitive capacity is called sensibility and remains worlds apart from the cognition of the object in itself even if one might see through to the very bottom of it (the appearance)."
                ],
                [["a45", "b62"],
                    "The Leibnizian-Wolffian philosophy has therefore directed all investigations of the nature and origin of our cognitions to an entirely unjust point of view in considering the distinction between sensibility and the intellectual as merely logical, since it is obviously transcendental, and does not concern merely the form of distinctness or indistinctness, but its origin and content, so that through sensibility we do not cognize the constitution of things in themselves merely indistinctly, but rahter not at all, and, as soon as we take away our subjective constitution, the repsented object with the properties that sensible intuition attributes to it is nowhere to be encountered, nor can it be encountere, for it is just this subjective constitution that determines its form as appearance.<br>We ordinarily distinguish quite well between that which is essentially attached to the intuition of appearances, and is valid for every human sense in general, and that which pertains to them only contingently because it is not valid for the relation of sensibility in general but only for a particular situation or organization of this or that sense. And thus one calls the first cognition one that represents the object in itself, but the second one only its appearance. This distinction, however, is only empirical. If one stands by it (as commonly happens) and does nto regard that empirical intuition as in turn mere appearance (as ought to happen), so that there is nothing to be encountered in it that pertains to anything in itself, then our transcendental distinction is lost, and we believe ourselves to cognize things in themselves, thought we have nothing to do with anything except appearances anywhere (in the world of sense), even in the deepest research into its objects."
                ],
                [["a46", "b63"],
                    "Thus, we would certainly call a rainbow a mere appearance in a sun-shower, but would call this rain the thing in itself, and this is correct, as long as we understand the latter concept in a merely physical sense, as that which in universal experience and all different positions relative to the senses is always determined thus and not otherwise in intuition. But if we consider this empirical object in general and, without turning to its agreement with every human sense, ask whether it (not the raindrops, since these, as appearances, are already empirical objects) represents an object in itself, then the question of the relation of the representation to the object is transcendental, and not only these drops are mere appearances, but even their round form, indeed even the space through which they fall are nothing in themselves, but only mere modifications or foundations of our sensible intuition; the transcendental object, however, remains unknown to us."
                ],
                [["a47", "b64"],
                    "The second important concern of our transcendental aesthetic is that it not merely earn some favor as a plausible hypothesis, but that it be as certain and indubitable as can ever be demanded of a theory that is to serve as an organon. In order to make this certainty fully convincing we will choose a case in which its validity can become obvious <and that can serve to make that which has been adduced in 3 even more clear>.<br>Thus, if it were to be supposed that space and time are in themselves objective and conditions of the possibility of things in themselves, then it would be shown, first, that there is a large number of a priori apodictic and synthetic propositions about both, but especially about space, which we will therefore here investigate as our primary example. Since the propositions of geometry are cognized synthetically a priori and with apodictic certainty, I ask: Whence do you take such propositions, and on what does our understanding rely in attaining to such absolutely necessary and universally valid truths? There is no other way than through concepts or through intuitions, both of which, however, are given, as such, either a priori or a posteriori. The latter, namely empirical concept, together with that on which they are grounded, empirical intuition, cannot yield any synthetic proposition except one that is also merely empirical, i.e., a proposition of experience; "
                ]
            ]
        ]
    ],
    ["Second Part, Transcendental Logic",
        ["Introduction",
            ["The Idea of a Transcendental Logic",
                ["I. On logic in general.",
                    [["a50", "b74"], 
                        "Our cognition arises from two fundamental sources in the mind, the first of which is the reception of representations (the receptivity of impressions), the second the faculty for cognizing an object by means of these representations (spontaneity of concepts); through the former an object is given to us, through the latter it is thought in relation to that representation (as a mere determination of the mind). Intuition and concepts therefore constitute the elements of all our cognition, so that neither concepts without intuition corresponding to them in some way nor intuition without concepts can yield a cognition. Both are either pure or empirical. Empirical, if sensation (which presupposes the actual presence of the object) is contained therein; but pure if no sensation is mixed into the representation. One can call the latter the matter of sensible cognition."
                    ],
                    [["a51", "b75"],
                        "Thus pure intuition contains merely the form under which something is intuited, and pure concept only the form of thinking of an object in general. Only pure intuitions or concepts alone are possible a priori, empirical ones only a posteriori.<br>If we will call the receptivity of our mind to receive representations insofar as it is affected in some way sensibility, then on the contrary the faculty for bringing forth representations itself, or the spontaneity of cognition, is the understanding. It comes along with our nature that intuition can never be other than sensible, i.e., that it contains only the way in which we are affected by objects. The faculty for thinking of objects of sensible intuition, on the contrary, is the understanding. Neither of these properties is to be preferred to the other. Without sensibility no object would be given to us, and without understanding none would be thought. Thoughts without content are empty, intuitions without concepts are blind. It is thus just as necessary to make the mind's concepts sensible (i.e., to add an object to them in intuition) as it is to make its intuitions understandable (i.e., to bring them under concepts). Further these two faculties or capacities cannot exchange their functions. The understanding is not capable of intuiting anything, and the senses are not capable of thinking anything."
                    ],
                    [["a52", "b76"],
                        "Only from their unification can cognition arise. But on this account one must not mix up their roles, rather one has great cause to separate them carefully from each other and distinguish them. Hence distinguish the science of the rules of sensibility in general, i.e., aesthetic, from the science of the rules of understanding in general, i.e., logic.<br>Now logic in turn can be undertaken with two different aims, either as the logic of the general or of the particular use of the understanding. The former contains the absolutely necessary rules of thinking, without which no use of the understanding takes place, and it therefore concerns these rules without regard to the difference of the objects to which it may be directed. The logic of the particular use of the understanding contains the rules for correctly thinking about a certain kind of objects. The former can be called elementary logic, the latter, however, the organon of this or that science. In the schools the latter is often stuck before the sciences as their propaedeutic, thought in the course of human reason they are certainly the latest to be reached, once the science is already long complete, and requires only the final touch for its improvement and perfection. For one must already know the objects rather well if one will offer the rules for how a science of them is to be brought about."
                    ],
                    [["a53", "b77"],
                        "Now general logic is either pure or applied logic. In the former we abstract from all empirical conditions under which our understanding is exercised, e.g., from the influence of the senses, from the play of the imagination, the laws of memory, the power of habit, inclination, etc., hence also from the sources of prejudice, indeed in general from all causes from which certain cognitions arise or may be supposed to arise, because these merely concern the understanding under certain circumstances of its application, and experience is required in order to know these. A general but pure logic therefore has to do with strictyl a prior principles, and is a canon of the understanding and reason, but only in regard to what is formal in their use, be the content what it may (empirical or transcendental). A general logic, however, is then called applied if it is directed to the rules of the use of the understanding under the subjective empirical conditions that psychology teaches us. It therefore has empirical principles, although it is to be sure general insofar as it concerns the use fo the understanding without regard to the difference of objects."
                    ],
                    [["a54", "b78"],
                        "On this account it is also neither a canon of the understanding in general nor an organon of particular sciences, but merely a cathartic of the common understanding.<br>In general logic the part that is to constitute the pure doctrine of reason must therefore be entirely separated from that which constitutes applied (though still general) logic. The former alone is properly science, although brief and dry, as the scholastically correct presentation of a doctrine of the elements of the understanding requires. In this therefore logicians must always have two rules in view.<br>1) As general logic it abstracts from all contents of the cognition of the understanding and of the difference of its objects, and has to do with nothing but the mere form of thinking.<br>2) As pure logic it has no empirical principles, thus it draws nothing from psychology (as one has occasionally been persuaded), which therefore has no influence at all on the canon of the udnerstanding. It is a proven doctrine, and everything in it must be completely a priori."
                    ],
                    [["a55", "b79"],
                        "What I call applied logic (in opposition to the common signification of this word, according to which it ought to contain certain exercises to which pure logic gives the rule) is thus a representation of the understanding and the rules of its necessary use in concreto, namely under the contingent conditions of the subject, which can hinder or promote this use, and which can all be given only empirically. It deals with attention, its hindrance and consequences, the cause of error, the condition of doubt, of reservation, of conviction, etc., and general and pure logic is related to it as pure morality, which contains merely the necessary moral laws of a free will in general, is related to the doctrine of virtue proper, which assesses these laws under the hindrances of the feelings, inclinations, and passions to which human beings are more or less subject, and which can never yield a true and proven science, since it requires empirical and psychological principles just as much as that applied logic does."
                    ]
                ],
                ["II. On transcendental logic.",
                    [["a56", "b80"],
                        "General logic abstract, as we have shown, from all content of cognition, i.e. from any relation of it to the object, and considers only the logical form in the relation of cognitions to one another, i.e., the form of thinking in general. But now since there are pure as well as empirical intuitions (as the transcendental aesthetic proved), a distinction between pure and empirical thinking of objects could also well be found. In this case there would be a logic in which one did not abstract from all content of cognition; for that logic that contained merely the rules of the pure thinking of an object would exclude all those cognitions that were of empirical content. It would therefore concern the origin of our cognitions of objects insofar as that cannot be ascribed to the objects; while general logic, on the contrary, has nothing to do with this origin of cognition, but rather considers repsentations, whether they are originally given a priori in ourselves or only empirically, merely in respect of the laws according to which the understanding brings them into relation to one another when it thinks, and therefore it deals only with the form of the understanding, which can be given to the representations wherever they may have originated."
                    ],
                    [["a57", "b81"],
                        "And here I make a remark the import of which extends to all of the following considerations, and that we must keep well in view, namely that not every a priori cognition must be called transcendental, but only that by means of which we cognize that and how certain representations (intuitions or concepts) are applied entirely a priori, or are possible (i.e., the possibility of cognition or its use a priori). Hence neither space nor any geometrical determination of it a priori is a transcendental representation, but only the cognition that these repsentations are not of empirical origin at all and the possibility that they can nevertheless be related a priori to objects of experience can be called transcendental. Likewise the use of space about all objects in generla would also be transcendental; but if it is restricted solely to objects of the senses, then it is called empirical. The difference between the transcendental and the empirical therefore belongs only to the critique of cognitions and does not concern their relation to their object."
                    ]
                ]
            ]
        ],
        ["Part One, Transcendental Analytic",
            [["a65", "b89"], "This Analytic is the analysis of the entirety of our a priori cognition into the elements of the pure cognition of the understanding. It is concerned with the following points: 1. That the concepts be pure and not empirical concepts. 2. That they belong not to intuition and to sensibility, but rather to thinking and understanding. 3. That they be elementary concepts, and clearly distinguished from those which are derived or composed from them. 4. That the table of them be complete, and that they entirely exhaust the entire field of pure understanding. Now this completeness of a science cannot reliably be assumed from a rough calculation of an aggregate put together by mere estimates; hence it is possible only by means of an idea of the whole of the a priori cognition of the understanding, an through the division of concepts that such an idea determines and that constitutes it, thus only through their connection in a system. The pure understanding separates itself completely not only from everything empirical, but even from all sensibility."],
            [["", "b90"], "It is therefore a unity that subsists on its own, which is sufficient by itself, and which is not to be supplemented by any external additions. Hence the sum total of its cognition will constitute a system that is to be grasped and determined under one idea, the completeness and articulation of which system can at the same time yield a touchstone of the correctness and genuineness of all the pieces of cognition fitting into it. This whole part of the transcendental logic, however, consists of two books, the first of which contains the concepts of the pure understanding, the second its principles."],
            ["Book One, Analytic of Concepts",
                [["a66", "b91"], "I understand by an analytic of concepts not their analysis, or the usual procedure of philosophical investigations, that of analyzing the content of concepts that present themselves and bringing them to distinctness, but rather the much less frequently attempted analysis of the faculty of the understanding itself, in order to research the possibility of a priori concepts by seeking them only in the understanding as their birthplace and analyzing its pure use in general, for this is the proper business of a transcendental philosophy; the rest is the logical treatment of concepts in philosophy in general. We will therefore puruse the pure concepts into their first seeds and predispositions in the human understanding, where they lie ready, until with the opportunity of experience they are finally developed and exhibited in their clarity by the very same understanding, liberated from the empirical conditions attaching to them."],
                ["First Chapter, On the Clue to the discovery of all Pure Concepts of the Understanding",
                    [["a67", "b92"], "If one sets a faculty of cognition into play, then on various occasions different concepts will become prominent that will make this faculty known and that can be collected in a more or less exhaustive treatise depending on whether they have been observed for a longer time or with greater acuteness. Where this investigation will be completed can never be determined with certainty by means of this as it were a mechanical procedure."]
                ]
            ],
            ["Book Two, Analytic of Principles",
                ["Chapter One, On the schematism of the pure concepts of the understanding"],
                ["Chapter Two, System of all principles of pure understanding",
                    ["The System of the Principles of Pure Understanding",
                        ["First Section, On the supreme principle of all analytic judgments."],
                        ["Second Section, On the supreme principle of all synthetic judgments."],
                        ["Third Section, Systematic representation of all synthetic principles of pure understanding.",
                            ["Axioms of Intuition"],
                            ["Anticipations of Perception"],
                            ["Analogies of Experience",
                                [["a177", "b219"], "[First edition:]<br>Their general principle is: As regards their existence, all appearances stand a priori under rules of the determination of their relation to each other in one time.<br>[In the second edition:]<Their principle is: Experience is possible only through the representation of a necessary connection of perceptions.><br><Proof<br>Experience is an empirical cognition, i.e., a cognition that determines an object through perceptions. It is therefore a synthesis of perceptions, which is not itself contained in perception but contains the synthetic unity of the manifold of perception in one consciousness, which constitutes what is essential in a cognition of objects of the senses, i.e., of experience (not merely of the intuition or sensations of the senses), Now in experience, to be sure, perceptions come together only contingently, so that no necessity of their connection is or can become evident in the perceptions themselves, since apprehension is only a juxtaposition of the manifold of empirical intuition, but no representation of the necessity of the combined existence of the appearances that it juxtaposes in space and time is to be encountered in it. But since experience is a cognition of objects through perception, consequently the relation in the existence of the manifold is to be represented in it not as it is juxtaposed in time but as it is objectively in time, yet since time itself cannot be perceived, the determination of the existence of objects in time can only come about through their combination in time in general, hence only through a priori connecting concepts. Now since these always carry necessity along with them, experience is thus possible only through a representation of the necessary connection of the perceptions.><br>The three modi of time are persistence, succession, and simultaneity. Hence three rules of all temporal relations of appearances, in accordance with which the existence of each can be determined with regard to the unity of all time, precede all experience and first make it possible."],
                                [["a178", "b220"], "The general principle of all three analogies rests on the necessary unity of apperception with regard to all possible empirical consciousness (of perception) at every time, consequently, since that is an a priori ground, it rests on the synthetic unity of all appearances according to their relations in time. For the original apperception is related to inner sense (the sum of all representations), and indeed related a priori to its form, i.e., the relation of the manifold empirical consciousness in time. Now in the original apperception all of this manifold, so far as its temporal relations are concerned, is to be unified;"],
                                ["First Analogy, Principle of the persistence <of substance.>"]
                            ],
                            ["The postulates of empirical thinking in general", 
                                [["a219", "b266"], "1. Whatever agrees with the formal conditions of experience (in accordance with intuition and concepts) is possible.<br>2. That which is connected with the material conditions of experience (of sensation) is actual.<br>3. That whose connection with the actual is determined in accordance with general conditions of experience is (exists) necessarily.<br>The categories of modality have this peculiarity: as a determination of the object they do not augment the concept to which they are ascribed in the least, but rather express only the relation to the faculty of cognition. If the concept of a thing is already entirely complete, I can still ask about this object whether it is merely possible, or also actual, or, if it is the latter, whether it is also necessary? No further determinations in the object itself are hereby thought; rather, it is only asked: how is the object itself (together with all its determinations) related to the understanding and its empirical use, to the empirical power of judgment, and to reason (in its application to experience)?"],                                  
                                [["a220", "b267"], "For this very reason the princinples of modality are also nothing further than definitions of the concepts of possibility, actuality, and necessity in their empirical use, and thus at the same time restrictions of all categories to merely empirical use, without any permission and allowance for their transcendental use. For if the categories are not to have a merely logical significance and analytically express the form of thinking, but are to concern things and their possibility, actuality, and necessity, then they must pertain to possible experience and its synthetic unity, in which alone objects of cognition are given.<br>The postulate of the possibility of things thus requires that their concept agree with the formal conditions of an experience in general. This, however, namely the objective form of experience in general, contains all synthesis that is requisite for the cognition of objects. A concept that includes a synthesis in it is to be held as empty, and does not relate to any object, if this synthesis does not belong to experience, either as borrowed from it, in which case it is an empirical concept, or as one on which, as a priori condition, experience in general (its form) rests, and then it is a pure concept, which nevertheless belongs to experience, since its object can be encountered only in the latter. For whence will one derive the character of the possibility of an object that is thought by means of a synthetic a priori concept, if not from the synthesis that constitutes the form of the empirical cognition of objects?"],
                                [["a221", "b268"], "That in such a concept no contradiction must be contained is, to be sure, a necessary logical condition; but it is far from sufficient for the objective reality of the concept. Thus in the concept of a figure that is enclosed between two straight lines there is no contradiction, for the concepts of two straight lines and their intersection contain no negation of a figure; rather the impossibility rests not on the concept in itself, but on its construction in space, i.e., on the conditions of space and its determinations; but these in turn have their objective reality, i.e., they pertain to possible things, because they contain in themselves a priori the form of experience in general."],
                                [["a222", "b269"], "We shall now make obvious the extensive utility and influence of this postulate of possibility. If I represent to myself a thing that persists, so that everything that changes merely belongs to its states, I can never cognize from such a concept alone that such a thing is possible. Or, if I represent something to myself that is so constituted that if it is posited something else always and inevitably succeeds it, this may well be able to be so thought without contradiction; but whether such a property (as causality) will be encountered in any possible thing cannot thereby be judged. Finally, I can represent various things (substances) to myself that are so constituted that the state of one is followed by a consequence in the state of the other, and conversely; but whether such a relation can pertain to any things cannot be derived from these concepts, which contain a merely arbitrary synthesis. Thus only from the fact that these concepts express a priori the relations of the perceptions in every experience does one cognize their objective reality, i.e., their transcendental truth, and, to be sure, independently of experience, but yet not independently of all relation to the form of an experience in general and the synthetic unity in which alone objects can be empirically cognized."],
                                [["a223", "b270"], "But if one wanted to make entirely new concepts of substances, of forces, and of interactions from the material that perception offers us, without borrowing the example of their connection from experience itself, then one would end up with nothing but figments of the brain, for the possibility of which there would be no indications at all, since in their case one did not accept experience as instructress nor borrow these concepts from it. Invented concepts of this sort cannot acquire the character of their possibility a priori, like the categories, as conditions on which all experience depends, but only a posteriori, as ones given through experience itself, and their possibility must either be cognized a posteriori and empirically or not cognized at all. A substance that was persistently present in space yet without filling it (like that intermediate thing between matter and thinking beings, which some would introduce), or a special fundamental power of our mind to intuit the future (not merely, say, to deduce it), or, finally, a faculty of our mind to stand in a community of thoughts with other men (no matter how distant they may be) - these are concepts the possibility of which is entirely groundless, because it cannot be grounded in experience and its known laws, and without this it is an arbitrary combination of thoughts that, although it contains no contradiction, still can make no claim to objective reality, thus to the possibility of the sort of object that one would here think. As far as reality is concerned, it is evidently intrinsically forbidden to think it in concreto without getting help from erxperience, because it can only pertain to sensation, as the matter of experience, and does not concern the form of the relation that one can always play with in fictions."],
                                [["a224", "b271"], "But I leave aside everything the possibility of which can only be derived from actuality in experience, and consider here only the possibility of things through concepts a priori, about which I proceed to assert that it can never occur by itself solely from such concepts, but always only as formal and objective conditions of an experience in general. It may look, to be sure, as if the possibility of a triangle could be cognized from its concept in itself (it is certainly independent of experience); for in fact we can give it an object entirely a priori, i.e., construct it. But since this is only the form of an object, it would still always remain only a product of the imagination, the possibility of whose object would still remain doubtful, as requiring something more, namely that such a figure be thought solely under those conditions on which all objects of experience rest. Now that space is a formal a priori conditions of outer experiences, that this very same formative synthesis by means of which we construct a figure in imagination is entirely identical with that which we exercise in the apprehension of an appearance in order to make a concept of experience of it - it is this alone that connects with this concept the representation of the possibility of such a thing. And thus the possibility of continuous magnitudes, indeed even of magnitudes in general, since the concepts of them are all synthetic, is never clear from the concepts themselves, but only from them as formal conditions of the determination of objects in experience in general; and where should one wat to seek objects that correspond to the concepts, if not in the experience through which alone objects are given to us? - although without anticipating experience itself we can cognize and characterize the possibility of things solely in relation to the formal conditions under which something can be determined as an object in experience at all, thus fully a priori but only in relation to these conditions and whitin their boundaries."],
                                [["a225", "b273"], "The postulate for cognizing the actuality of things requires percetion, thus sensation of which one is conscious - not immediate perception of the object itself the existence of which is to be cognized, but still its connection with some actual perception in accordance with the analogies of experience, which exhibit all real connection in an experience in general.<br>In the mere concept of a thing no characteristic of its existence can be encountered at all. For even if this concept is so complete that it lacks nothing required for thinking of a thing with all of its inner determinations, still existence has nothing in the least to do with all of this, but only with the question fo whether such a thing is given to us in such a way that the perception of it could in any case precede the concept. For that the concept precede the perception signifies its mere possibility; but perception, which yields the material for the concept, is the sole characteristic of actuality. However, one can also cognize the existence of the thing prior to the perception of it, and therefore cognize it comparatively a prior, if only it is connected with some perceptions in accordance with the principles of their empirical connection (the analogies)."],
                                [["a226", "b274"], "For in that case the existence of the thing is still connected with our perceptions in a possible experience, and with the guidance of the analogies we can get from our actual perceptions to the thing in the series of possible perceptions. Thus we cognize the existence of a magnetic matter penetrating all bodies from the perception of attracted iron filings, although an immediate perception of this matter is impossible for us given the constitution of our organs. For in accordance with the laws of sensibility and the context of our perceptions we could also happen upon the immediate empirical intuition of it in an experience if our senses, the crudeness of which does not affect the form of possible experience in general, were finer. Thus wherever perception and whatever is appended to it in accordance with empirical laws reaches, there too reaches our cognition of the existence of things. If we do not begin with experience, or proceed in accordance with laws of the empirical connection of appearances, then we are only making a vain display of wanting to discover or research the existence of any thing. <However, a powerful objection against these rules for proving existence mediately is made by idealism, the refutation of which belongs here."]
                            ],
                            ["Refutation of Idealism",
                                [["a227", "b275"], "Idealism (I mean material idealism) is the theory that declares the existence of objects in space outside us to be either merely doubtful and indemonstrable, or else false and impossible; the former is the problematic idealism of Descartes, who declares only one empirical assertion (assertio), namely I am, to be indubitable; the latter is the dogmatic idealism of Berkeley, who declares space, together with all the things to which it is attached as an inseparable condition, to be something that is impossible in tiself, and who therefore also declares things in space to be merely imaginary. Dogmatic idealism is unavoidable if one regards space as a property that is to pertain to the things in themselves; for then it, along with everything for which it serves as a condition, is a non-entity. The ground for this idealism, however, has been undercut by us in the Transcendental Aesthetic. Problematic idealis, which does not assert anything about this, but rather professes only our incapacity for proving an existence outside us from our own by means of immediate experience, is rational and appropriate for a thorough philosophical manners of thought, allowing, namely, no decisive judgment until a sufficient proof has been found. The proof that is demanded must therefore establish that we have experience and not merely imagination of outer things, which cannot be accomplished unless one can prove that even our inner experience, undoubted by Descartes, is possible only under the presupposition of outer experience."],
                                [["a228", "b276"], "Theorem<br>The mere, but empirically determined, consciousness of my own existence proves the existence of objects in space outside me.<br>Proof<br>I am conscious of my existence as determined in time. All time-determination presupposes something persistent in perception. This persistent thing, however, cannot be something in me, since my own existence in time can first be determined only through this persisten tthing. Thus the perception of this persistent thing is possible only through a thing outside me and not through the mere representation of a thing outside me. Consequently, the determination of my existence in time is possible only by means of the existence of actual things that I perceive outside myself. Now consciousness in time is necessarily combined with the consciousness of the possibility of this time-determination: Therefore it is also necessarily combined with the existence of the things outside me, as the condition of time-determination; i.e., the consciousness of my own existence is at the same time an immediate consciousness of the existence of other things outside me."],
                                [["", "b277"], "Note 1. One will realize that in the preceding proof the game that idealism plays has with greater justice been turned against it. Idealism assumed that the only immediate experience is inner experience, and that from that outer things could only be inferred, but, as in any case in which one infers from given effects to determinate causes, only unreliably, since the cause of the representations that we perhaps falsely ascribe to outer things can also lie in us. Yet here it is proved that outer experience is really immediate, that only by means of it is possible not, to be sure, the consciousness of our own existence, but its determination in time, i.e., inner experience. Of course, the representation I am, which expresses the consciousness that can accompany all thinking, is that which immediately includes the existence of a subject in itself, but not yet any cognition of it, thus not empirical cognition, i.e., experience; for to that there belongs, besides the thought of something existing, intuition, and in this case inner intuition, i.e., time, in regard to which the subject must be determined, for which outer objects are absolutely requisite, so that inner experience itself is consequently only mediate and possible only through outer experience."],
                                [["", "b278"], "Note 2. All use of our faculty of cognition in experience for the determination of time agrees with this completely. Not only can we perceive all time-determination only through the change in outer relations (motion) relative to that which persists in space (e.g., the motion of the sun with regard to the objects on the earth); we do not "]

                            ]
                        ]
                    ]
                ],
                ["Chapter Three, On the ground of the distinction of all objects in general into phenomena and noumena"]
            ]
        ],
        ["Part Two, Transcendental Dialectic",
            ["Book One, On the concepts of pure reason",
                ["First section, On the ideas in general."],
                ["Second section, On the transcendental ideas."],
                ["Third section, The system of transcendental ideas."]
            ],
            ["Book Two, The dialectical inferences of pure reason",
                ["Chapter One, The paralogisms of pure reason",
                    ["First paralogism, of substantiality"],
                    ["Second paralogism, of simplicity"],
                    ["Third paralogism, of personality"],
                    ["Fourth paralogism, of the ideality (of outer relation)"]
                ],
                ["Chapter Two, The antinomy of pure reason",
                    ["First Section, The system of cosmological ideas."],
                    ["Second Section, Antithetic of pure reason.",
                        ["First Conflict of the Transcendental Ideas"],
                        ["Second Conflict of the Transcendental Ideas"],
                        ["Third Conflict of the Transcendental Ideas"],
                        ["Fourth Conflict of the Transcendental Ideas"]
                    ],
                    ["Third Section, On the interest of reason in these conflicts."],
                    ["Fourth Section, The transcendental problems of pure reason, insofar as they absolutely must be capable of a solution."],
                    ["Fifth Section, Skeptical representation of the cosmological questions raised by all four transcendental ideas."],
                    ["Sixth Section, Transcendental idealism as the key to solving the cosmological dialectic."],
                    ["Seventh Section, Critical decision of the cosmological conflict of reason with itself."],
                    ["Eigth Section, The regulative principle of pure reason in regard to the cosmological ideas."],
                    ["Ninth Section, On the empirical use of the regulative principle of reason, in regard to all cosmological ideas."]
                ],
                ["Chapter Three, The ideal of pure reason",
                    ["Section One, The ideal in general."],
                    ["Section Two, The transcendental ideal (Prototypon transcendentale)",
                        [["a572", "b600"],
                        "."]
                    ],
                    ["Section Three, The grounds of proof of speculative reason for inferring the existence of a highest being.",
                        [["a584", "b612"],
                        "."]
                    ],
                    ["Section Four, On the impossibility of an ontological proof of God's existence."
                    ],
                    ["Section Five, On the impossibility of a cosmological proof of God's existence."
                    ],
                    ["Section Six, On the impossibility of a physico-theological proof"
                    ],
                    ["Section Seven, Critique of all theology from specualtive principles of reason.",
                        ["Appendix to the Transcendental Dialectic",
                            ["On the regulative use of the ideas of pure reason.",
                                [
                                    ["a642", "b670"],
                                    "The outcome of all dialectical attempts of pure reason not only confirms what we have already proved in the Transcendental Analytic, namely that all the inferences that would carry us out beyond the field of possible experience are deceptive and groundless, but it also simultaneously teaches us this particular lesson: that human reason has a natural propensity to overstep all these boundaries, and that transcendental ideas are just as natural to it as the categories are to the understanding, although with this difference, that just as the categories lead to truth, i.e, to the agreement of our concepts with their objects, the ideas effect a mere, but irresistible, illusion, deception by which one can hardly resist even through the most acute criticism."
                                ],
                                [
                                    ["a643", "b671"],
                                    "Everything grounded in the nature of our powers must be purposive and consistent with their correct use, if only we can guard a certain misunderstanding and find out their proper direction. Thus the transcendental ideas too will presumably have a good and consequently immanent use, even though, if their significance is misunderstood they are taken for concepts of real things, they can be transcendent in their application and for that very reason deceptive. For in regard to the whole of possible experience, it is not the idea itself but only its use that can be either extravagant (transcendent) or indigenous (immanent), according to whether one directs them straightway to a supposed object corresponding to them, or only to the use of the understanding in general regarding the objects with which it has to do; and all errors of subreption are always to be ascribed to a defect in judgment, never to understanding or to reason."
                                ],
                                [
                                    ["a644", "b672"],
                                    "Reason never relates directly to an object, but solely to the understanding and by means of it to reason's own empirical use, hence it does not create any concepts (of objects) but only orders them and gives them that unity which they can have in their greatest possible extension, i.e., in relation to the totality of series; the understanding does not look to this totality at all, but only to the connection through which series of conditions always come about according to concepts. Thus reason really has as object only the understanding and its purposive application, and just as the understanding unites the manifold into an object through concepts, so reason on its side unites the manifold of concepts through ideas by positing a certain collective unity as the goal of the understanding's actions, which are otherwise concerned only with distributive unity."
                                ],
                                [
                                    ["a645", "b673"], 
                                    "Accordingly, I assert: the transcendental ideas are never of constitutive use, so that the concepts of certain objects would thereby be given, and in case one so understand them, they are merely sophistical (dialectical) concepts. On the contrary, however, they have an excellent and indispensably necessary regulative use, namely that of directing the understanding to a certain goal respecting which the lines of direction of all its rules converge at one point, which, although it is only an idea (focus imaginarius) - i.e., a point from which the concepts of the understanding do not really proceed, since it lies entirely outside the bounds of possible experience - nonetheless still serves to obtain for these concepts the greatest unity alongside the greatest extension. Now of course it is from this that there arises the deception, as if these lines of direction were shot out from an object lying outside the field of possible empirical cognition (just as objects are seen behind the surface of a mirror); yet this illusion (which can be prevented from deceiving) is nevertheless indispensably necessary if besides the objects before our eyes we want to see those that lie far in the background, i.e., when, in our case, the understanding wants to go beyond every given experience (beyond this part of the whole of possible experience), and hence wants to take the measure of its greatest possible and uttermost extension."
                                ],
                                [
                                    ["a646", "b674"], 
                                    "If we survey the cognitions of our understanding in their entire range, then we find that what reason quite uniquely prescribes and seeks to bring about concerning it is the systematic in cognition, i.e., its interconnection based on one principle. This unity of reason always presupposes an idea, namely that of the form of a whole of cognition, which precedes the determinate cognition of the parts and contains the conditions for determining a priori the place of each part and its relation to the others. Accordingly, this idea postulates complete unity of the understanding's cognition, through which this cognition comes to be not merely a contingent aggregate but a system interconnected in accordance with necessary laws. One cannot properly say that this idea is the concept of an object, but only that of the thoroughgoing unity of these concepts, insofar as the idea serves the understanding as a rule. Such concepts of reason are not created by nature, rather we question nature according to these ideas, and we take out cognition to be defective as long as it is not adequate to them. Admittedly, it is hard to find pure earth, pure water, pure air, etc. Nevertheless, concepts of them are required (through as far as their complete purity is concerned, have their origin only in reason) in order appropriately to determine the share that each of these natural causes has in appearance; thus one reduces all materials to earths (mere weight, as it were), to salts and combustibles (as force), and finally to water and air as vehicles (machines, as it were, by means of which the aforementioned operate), in order to explain the chemical effects of materials in accordance with the idea of a mechanism. For even though it is not actually expressed this way, it is still very easy to discover the influence of reason on the classifications of students of nature."
                                ],
                                [
                                    ["a647", "b675"], 
                                    "If reason is the faculty of deriving the particular from the universal, then: Either the universal is in itself certain and given, and only judgment is required for subsuming, and the particular is necessarily determined through it. This I call the 'apodictic' use of reason. Or the universal is assumed only problematically, and it is a mere idea, the particular being certain while the universality of the rule for this consequent is stil a problem; then several particular cases, which are all certain, are tested by the rule, to see if they flow from it, and in the case in which it seems that all the particular cases cited follow from it, then the universality of the rule is inferred, including all subsequent cases, even those that are not given in themselves. This I will call the 'hypothetical' use of reason. The hypothetical use of reason, on the basis of ideas as problematic concepts, is not properly constitutive, that is, not such that if one judges in all strictness the truth of the universal ruel assumed as a hypothesis thereby follows, for how is one to know all possible consequences, which would prove the universality of the assumed principle if they followed from it? Rather, this use of reason is only regulative, bringing unity into particular cognitions as far as possible and thereby approximating the rule to universality."
                                ],
                                [
                                    ["a648", "b676"], 
                                    "The hypothetical use of reason is therefore directed at the systematic unity of the understanding's cognitions, which, however, is the touchstone of truth for its rules. Conversely, systematic unity (as mere idea) is only a projected unity, which one must regard not as given in itself, but only as a problem; this unity, however, helps to find a principle for the manifold and particular uses of the understanding, thereby guiding it even in those cases that are not given and making it coherently connected. From this, however, one sess only that systematic unity or the unity of reason of the manifold of the understanding's cognition is a logical princinple, in order, where the udnerstanding alone does not attain rules, to help it through ideas, simultaneously creating unanimity among its various rules under one principle (the systematic), and thereby interconnection, as far as this can be done. But whether the constitution of objects or the nature of the understanding that cognizes them as such are in themselves determined to systematic unity, and whether one could in a certain measure postulate this a priori without taking into account such an interest of reason, and therefore say that all possible cognitions of the understanding (including empirical ones) have the unity of reason, and stand under common principles from which they could be derived despite their variety: that would be a transcendental principle of reason, which would make systematic unity not merely something subjectively and logically necessary, as method, but objectively necessary."
                                ],
                                [
                                    ["a649", "b677"],
                                    "We will illustrate this through one case in which reason is used. Among the different kinds of unity according to concepts of the understanding belongs the causality of a substance, which is called 'power.' At first glance the various appearances of one and the same substance show such diversity that one must assume almost as many powers as there are effects, as in the human mind there are sensation, consciousness, imagination, memory, wit, the power to distinguish, pleasure, desire, etc. Initially a logical maxim bids us to reduce this apparent variety as far as possible by discovering hidden identity through comparison, and seeing if imagination combined with consciousness may not be memory, wit, the power to distinguish, or perhaps even understanding and reason. The idea of a fundamental power - though logic does not at all ascertain whether there is such a thing - is at least the problem set by a systematic representation of the manifoldness of powers. The logical principle of reason demands this unity as far as it is possible to bring it about, and the more appearances of this power and that power are found to be identical, the more probable it becomes that they are nothing but various expressions of one and the same power, which can be called (comparatively) their fundamental power. one proceeds in just the same way with the rest of the powers."
                                ],
                                [
                                    ["a650", "b678"],
                                    "These comparatively fundamental powers must once again be compared with one another, so as to discover their unanimity and thereby bring them close to a single radical, i.e., absolutely fundamental, power. But this unity of reason is merely hypothetical. One asserts not that such a power must in fact be found, but rather that one must sekk it for the benefit of reason, namely for setting up certain principles for the many rules with which experience may furnish us, and that where it can be done, one msut in such a way bring systematic unity into cognition.<br>But if one attends to the transcendental use of the understanding, it is evident that this idea of a fundamental power in general does not function merely as a problem for hypothetical use, but pretends to obtain objective reality, so that the systematic unity of a substance's many powers are postulated and an apodictic principle of reason is erected. For even without our having attempted to find the unanimity among the many powers, or indeed even when all such attempts to discover it have failed, we nevertheless presuppose that such a thing will be found; and it is not only, as in the case cited, on account of the unity of substance that reason presupposes systematic unity among manifold powers, but rather reason does so even where many powers, though to a certain degree of the same kind, are found, as with matter in general, where particular natural laws stand under more general ones; and the parsimony of principles is not merely a principle of economy of reason, but becomes an inner law of its nature."
                                ],
                                [
                                    ["a651", "b679"],
                                    "In fact it cannot even be seen how there could be a logical principle of rational unity among rules unless a transcendental principle is presupposed, through which such a systematic unity, as pertaining to the object itself, is assumed a priori as necessary. For by what warrant can reason in its logical use claim to treat the manifoldness of the powers which nature gives to our cognition as merely concealed unity, and to derive them as far as it is able from some fundamental power, when reason is free to admit that it is just as possible that all powers are different in kind, and that its derivation of them from a systematic unity is not in conformity with nature? For then reason would proceed directly contrary to its vocation, since it would set as its goal an idea that entirely contradicts the arrangement of nature. Nor can one say that it has previously gleaned this unity from the contingent constitution of nature in accordance with its principles of reason. For the law of reason to seek unity is necessary, since without it we would have no reason, and without that, no coherent use of the understanding, and, lacking that, no sufficientm ark of empirical truth; thus in regard to the latter we simply have to presuppose the systematic unity of nature as objectively valid and necessary."
                                ]
                            ]
                        ]
                    ]
                ]
            ]
        ]
    ]
],
["Transcendental Doctrine of Method"]
        ]
}
// return true if a document with the code exists, false otherwise
function exists(code: string){
    if (bank[code] == undefined){
        return false;
    } else {
        return true;
    }
}
// adds new document to the bank
function addDocument(title: string, author: string, code: string){
    if (!exists(code)){
        bank[code] = [title];
    }
}
function removeDocument(code: string){
    if (exists(code)){
        bank[code] = undefined;
        return "Document with code '"+code+"' removed from registry.";
    } else {
        return "Document with that code doesn't exist.";
    }
}
// adds section immediately after some location, which can point to either a passage or a section
function addSection(code: string, s: string, location: string){
    if (exists(code)){
        let pLocation = JSON.parse(location);
        let count = 0;
        let iter = bank[code];
        try {
            while(count<pLocation.length-1){
                iter=iter.at(pLocation[count]);
                count++;
            }
        } catch (error) {
            return "Location is invalid.";
        }
        iter.splice(pLocation[pLocation.length-1]+1, 0, [s]);
        return "Section added.";
    }
}
// adds passage immediately after some location, which can point to either a passage or a section
function addPassage(code:string, index: string, p: string, location: string){
    if (exists(code)){
        let pLocation = JSON.parse(location);
        let count = 0;
        let iter = bank[code];
        try {
            while(count<pLocation.length-1){
                iter=iter.at(pLocation[count]);
                count++;
            }
        } catch (error) {
            return "Location is invalid.";
        }
        iter.splice(pLocation[pLocation.length-1]+1, 0, [index.indexOf(",")==-1 ? index : index.split(","), p]);
        return "Added passage.";
    }
}

function removeSection(code: string, s: string){

}

function removePassage(code: string, index: string){

}

// downloads whole bank
function downloadBank(){
    return bank;
}
export { bank, addDocument, removeDocument, addSection, addPassage }